### ISSUE TITLE
No Selected Year

### ISSUE THREAD

**Issue by H077y** [systemic-chaos/currently-fronting#193]
This may be more of a suggestion than an issue, but I have recently discovered that PluralKit sees the year 0004 as a null year.
Members can input their age using 0004 as the year, and PluralKit will hide the year from the member's profile.
![image](https://user-images.githubusercontent.com/64114013/202908476-244af321-e9cb-4dde-8989-02961f502dae.png)

I just wanted to know if this could be added to front.plural.codes as it currently still shows 0004 as the year :3
![image](https://user-images.githubusercontent.com/64114013/202908517-849c3c07-0fad-476a-92b1-8189f3b3f89a.png)

**Comment by ArcanaOfSouls** [comment]
Hey~

We are indeed aware of the date handling in question!

Our opinion on the issue diverges from that of the PluralKit development team in that we view the use of a specific year as a `null` value to be a flawed implementation. This is most notable in cases of systems with members who are far older than their physical form. Our collective, for example, has an entity that is several thousand years old. If such a headmate were to identify with a year of birth of 4 CE, they would never be able to display that in a profile on the PluralKit Dashboard or PluralKit itself due to the implementation of 4 CE as a `null` value.

That said, we will include a query parameter as an opt-in to this particular handling of 4 CE. It will be added along with the other new query parameters planned for a near-future release. We'll leave this issue open till that release for tracking purposes.

Once our dashboard is added shortly after that, it should be easier for folks to specify such parameters for each system that they're friends with.

**Unrelated to the issue content, but something to keep in mind for the future**: I removed one of the images included in the original issue, since it included screenshots of messages from Discord accounts other than your own, including the usernames. From our perspective, that constitutes an invasion of privacy when posted to a public site like GitHub unless you have explicit consent from the users involved. This is important in general from a courtesy perspective, but it's also worh noting that systems often have hidden members who may be participating in conversations; those systems would almost certainly not want those members' messages exposed publicly. (I also inadvertently deleted one other image included in this issue due to issues with the GitHub Mobile app, so feel free to add that back into the issue if desired.) *Please don't take this too harshly, as it's definitely not meant that way. Most people don't think about these things unless they've either had to contend with specifically targeted hate on the basis of their identity online or have experience working in cybersecurity. Both happen to be true in our case.* Thanks for understanding on this one! We just want to keep folks safe!

And finally: Thanks for taking such a sincere interest in this project. The enthusiasm is greatly appreciated. Please feel free to continue filing issues as things come up. :)

Sincerely,
Arcana

**Comment by ArcanaOfSouls** [comment]
Ohhhhh. We were thinking about the BCE aspect since the one of us who has existed thousands of years very likely predates Year 0. But fae haven't defined a precise year. And you're absolutely right: Based on the database schema for PluralKit, years prior to Year 0 would indeed be impossible to enter. That completely invalidates our perspective on making 4 CE as `null` an opt-in query parameter.

We'll treat this as a bugfix now and get it resolved in the next few days!

Thank you all so much for the insight! It's really nice to get additional eyes on the UX from an active user. This was an astute observation on your part. :)

Sincerely,
Arcana

**Comment by H077y** [comment]
Ahh that makes sense. We have a few dragons in our system that are over 2,000 so they've been setting their birthdays to 0001. But since learning about 0004, that makes it a lot easier to check.
I only really noticed because of the conversations in PluralKit about it, and wanted to check if the fronter website used it :3

I'm glad I can be of help, and I hope I can help further in the future.

**Comment by ArcanaOfSouls** [comment]
Hey again! This is still slated for a fix very soon, but we've been out of commission for the past few weeks due to an RSI flare-up. This will be the first thing we tackle once we finalize a build toolchain change that was ongoing behind the scenes before our hands became painful. The fact that we're typing this is a good sign of recovery, though. We'll let you know when this is taken care of. :)

**Comment by ArcanaOfSouls** [comment]
@H077y This should be resolved by #237. Please feel free to reach out if for some reason it isn't working.

Thanks again for reporting the issue! :3
