### ISSUE TITLE
a "switch-out" renders as a blank page

### ISSUE THREAD

**Issue by spiralw** [systemic-chaos/currently-fronting#201]
if my device isn't able to make requests to pluralkit's api, that *also* renders as a blank page. that is confusing, there should be a way to indicate the presence of a switch but the lack of any members, separately from indicating an error

**Comment by spiralw** [comment]
additionally, the tab title changes to the url text:
![image](https://user-images.githubusercontent.com/64013111/205504369-26c2cdb9-33a0-4c44-8d5a-1369482a26ea.png)

**Comment by ArcanaOfSouls** [comment]
Hey~

This was a deliberate design decision made in an effort to preserve privacy for users who for one reason or another keep fronters/members/switch-outs private or simply don't log switches. It was made in consultation with some of our earliest users who, like us, are extremely privacy conscious. While we recognize that the error is still exposed by the API and that this is a client-side app, there are easier ways to be intrusive about such things than viewing a page on our app and checking browser network logs. That would not necessarily be the case if we changed this behavior.

That said, out of respect for those users and ourselves, we won't be changing this behavior at present. We totally understand the confusion, but that confusion is intentional. If errors and switch-outs render the same way, then it is harder to discern one from the other, as intended.

Thanks for reporting this though!
Arcana

PS: We'll see about documenting this behavior in the README soon.
