### ISSUE TITLE
we're a bit confused.

### ISSUE THREAD

**Issue by webpsystem** [systemic-chaos/currently-fronting#205]
we don't mean to bother but we've been really confused on how to set this up/what to do/where to even begin. we've been really curious about doing this, since it seems like it'd work great for us. i've combed through it up and down, but i can't seem to understand anything... we'd really appreciate knowing how to set this up for ourselves, thank you. - s

**Comment by ArcanaOfSouls** [comment]
Hi @webpsystem! Thanks for reaching out! I assume you have a system created in PluralKit? If not, that is the first step. If you have one created, can you please send your five character system ID as a comment? That will help us figure out what steps to recommend for setup. :)

If you need help locating your system ID, feel free to let us know!

Kindest regards,
Arcana

**Comment by webpsystem** [comment]
zseda is our PluralKit code! Thanks! We've had it set up already, but was just confused with this. - K

**Comment by ArcanaOfSouls** [comment]
@webpsystem No worries! Glad to assist!

So, it looks like you haven't logged any switches in PluralKit. The list of current fronters is pulled from the current switch logged in PluralKit.

If your fronters are set to private in PluralKit, they won't be displayed. Data on a given member that is listed as private in PluralKit will also not be displayed. (There's unfortunately no way around the requirement for displayed details to be listed as public due to the way that the PluralKit API is designed at present.)

We know there are few third-party utilities for logging switches other than simply using bot commands, but we don't have links to them offhand. (We currently just use bot commands.)

Fundamentally, you'll want to start by logging a switch. If using the bot, the process is explained in the [PluralKit documentation](https://dash.pluralkit.me/). Note that a member can be referred to in a `pk;switch` command by member name or five character ID. Also, `pk;sw` is shorthand for `pk;switch`. If you regularly log switches, you might also consider enabling autoproxy for the first fronter by running `pk;ap front`; but that's unrelated to the functionality of this web application.

If you want to add more details to members, we recommend visiting the [PluralKit Dashboard](https://dash.pluralkit.me/). You can also make bulk updates to member privacy through the Dashboard, which might be useful if the data is private for all your members and you want to display certain fields publicly through `currently fronting`.

Feel free to let us know if you need any more assistance!

Sincerely,
Arcana

**Comment by webpsystem** [comment]
I see now! We set the switches on now, and we have also publicly displayed our system. We've only set up my profile for now, but we did everything. We're just confused on now how to set up/find the link to set it up onto our Discord. Thanks! - K

**Comment by webpsystem** [comment]
Wait actually we think we got it now! Thank you. <3 We just had to check something. We put our PluralKit code into the link and it works!

**Comment by ArcanaOfSouls** [comment]
@webpsystem Great! I'm so glad you figured it out~

And we really hope you find the app useful! If you have any suggestions for new features, or if you encounter a bug that needs fixing, please feel free to file another issue here. We'll be happy to take a look as we have time.

:)
